apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: puje2docker/auth_service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:                  # Environment variables supplied to the Pod
            - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
              valueFrom:          # Get the value of environment variable from kubernetes secrets
                secretKeyRef:
                  name: cassandra-auth-service-secrets
                  key: CASSANDRA_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-auth-service-secrets
                  key: CASSANDRA_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: cassandra-auth-service-secrets
                  key: CASSANDRA_URL
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: cassandra-auth-service-secrets
                  key: SERVER_PORT
            - name: jwt-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-secret
            - name: service-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: service-secret

  selector:
    matchLabels:
      app: auth-service
