apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  labels:
    app: orders-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: rustembayetov/orders_service
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: orders-service