apiVersion: apps/v1
kind: Deployment
metadata:
  name: pays-pp-service
  labels:
    app: pays-pp-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pays-pp-service
    spec:
      containers:
        - name: pays-pp-service
          image: rustembayetov/pays_pp_service
          ports:
            - containerPort: 8080
          env:
            - name: jwt-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-secret
            - name: service-secret
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: service-secret
  selector:
    matchLabels:
      app: pays-pp-service
