apiVersion: v1
kind: Service
metadata:
  name: pays-ba-service
  labels:
    app: pays-ba-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pays-ba-service