version: '2'
services:
  springbootapp:
    image: springbootapp:latest
    container_name: springbootapp
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://productdb:3306/springBatchDocker?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 4446:4446
    command: >
      /bin/bash -c "
              while ! nc -z productdb 3306;
              do
                echo sleeping;
                sleep 1;
              done;
              echo Connected!;
            "
  mariadb:
    image: mariadb:latest
    container_name: productdb
    volumes:
      - my-db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springBatchDocker
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
volumes:
  my-db:
